### ISSUE TITLE
Unidentified image error

### ISSUE THREAD

**Issue by SamuelleMollard** [itsron717/XKCD#8]
There was a problem with the command, a python error, here is the log

Traceback (most recent call last):
  File "/home/selene/.local/bin/xkcd", line 11, in <module>
    load_entry_point('xkcd==0.1', 'console_scripts', 'xkcd')()
  File "/home/selene/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/selene/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/selene/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/selene/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/selene/.local/lib/python3.6/site-packages/xkcd.py", line 29, in cli
    img = Image.open(BytesIO(res.content))
  File "/home/selene/.local/lib/python3.6/site-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f61173b5938>

I understand if you don't want to take time to fix this, but if you want to fix it you have the log now.
It doesn't seem easily reproductible, and happened with the xkcd --random command

**Comment by TheTechRobo** [comment]
Do you know which xkcd was used?

**Comment by MOLLARDAmbre** [comment]
No sorry, it's from a long time ago too
